# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$time$all'

# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = false

[character]
format = '$symbol '
success_symbol = '[ツ](green)'
error_symbol = '[ツ](yellow)'
vimcmd_symbol = '[ツ](blue)'

[package]
disabled = true

[cmd_duration]
show_notifications = true
min_time_to_notify = 30_000  # 30 s

[time]
disabled = false
format = '[$time]($style) '
style = ''
# rust chrono: %R Hour-minute format. Same to %H:%M.
time_format = '%R'

# 'via V' coming from *.v files
[vlang]
disabled = true
