#!/usr/bin/env bash
set -euo pipefail

# consider only numbered workspaces, possibly with a tag (like '3:foo')
workspace_nums=$(i3-msg -t get_workspaces \
  | jq --raw-output '.[].name' \
  | sed --quiet 's/^\([0-9]\+\):\?.*$/\1/p' \
  | sort
)
echo "workspace_nums: '$workspace_nums'"

first_available=$(awk '{ if (NR != $0) { print NR ; exit 0 } }' <<< "$workspace_nums")
# if no number was skipped, use max workspace number + 1
[[ -z "$first_available" ]] && first_available=$(($(tail -n 1 <<< "$workspace_nums") + 1))

CHANGE_WORKSPACE_CMD="workspace $first_available"

if [[ "${1:-}" = "--no-switch" ]]; then
  CHANGE_WORKSPACE_CMD=""
fi

i3-msg -t run_command "move window to workspace $first_available; $CHANGE_WORKSPACE_CMD" > /dev/null
