#!/usr/bin/env python

import operator

import i3ipc


# TODO handle empty workspaces on secondary output


def main():
    i3 = i3ipc.Connection()

    # gets a list of workspaces, sorted by num
    workspaces = sorted(i3.get_tree().workspaces(), key=operator.attrgetter("num"))

    # move the workspaces to their desired numbers
    for i, workspace in enumerate(workspaces):
        name_curr = workspace.ipc_data["name"]
        idx_target = i + 1

        name_split = name_curr.split(":", 1)
        suffix = f":{name_split[1]}" if len(name_split) > 1 else ""

        i3.command(f"rename workspace {name_curr} to {idx_target}{suffix}")


if __name__ == "__main__":
    main()
