#!/usr/bin/env python

import sys

import i3ipc


def main(tag):
    i3 = i3ipc.Connection()

    workspaces = i3.get_workspaces()
    # find the focused workspace
    curr_worskpace = next(filter(lambda s: s.focused, workspaces))

    prefix = curr_worskpace.name.split(":", 1)[0]
    # escape spaces in tag
    suffix = f":{tag.replace(' ', '-')}" if tag else ""

    i3.command(f"rename workspace current to {prefix}{suffix}")


if __name__ == "__main__":
    main(sys.argv[1])

